name: vsc_address_lookup_field
description: An address lookup field using the Google Places API.
version: 0.0.1
homepage: https://vscorp.com

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_place:
    git: https://github.com/dsyrstad/google_place.git
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
